# Generated by Django 3.1 on 2021-03-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places'),
        ('core_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.city'),
        ),
    ]
