# Generated by Django 3.1 on 2021-03-31 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places'),
        ('core_users', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workstations',
            field=models.ManyToManyField(null=True, to='places.Workstation'),
        ),
    ]
