# Generated by Django 3.1 on 2021-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0005_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
