# Generated by Django 3.1 on 2021-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
