# Generated by Django 3.1 on 2021-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstation',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(choices=[('Wrocław', 'Wroclaw'), ('Rzeszów', 'Rzeszow'), ('Inne', 'Inne')], default='Wrocław', max_length=20),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='workstation',
            field=models.CharField(choices=[('UX Designer', 'Ux'), ('UI Designer', 'Ui'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('PHP', 'Php'), ('Python', 'Python'), ('React', 'React'), ('Mobile', 'Mobile'), ('Scrum Master', 'Scrum Master'), ('Vue', 'Vue')], default='UX Designer', max_length=20),
        ),
    ]
