#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

./docker/django/wait-for-it.sh -t 300 postgres:5432
python manage.py migrate
python manage.py loaddata fixtures/places.json
python manage.py runserver_plus 0.0.0.0:8000 --cert-file /tmp/cert.crt
exec "$@"
